blog/urls.py
from django.urls import path
from blog import views
from .views import PostDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signup/message/<user>', views.blank_page, name='blank_page'),
    path('signout/', views.signout, name='signout'),
    path('post/create', views.create_post, name='create_post'),
    path('post/view/<pid>', views.post_view, name='post_view'),
    path('post/<int:pk>/<str:slug>', PostDetailView.as_view(), name='post_view'),
    path('profile/update/<pk>', views.update_profile, name='update_profile'),
    path('project/view/<str:pk>', views.project_view, name='project_view'),
    path('post/view/', views.post_view, name='posts_view'),
    path('blogs/view/', views.blog_view, name='blog_view'),
    path('project/add/', views.add_project, name='add_project'),
    path('project/update/<str:id>', views.update_project, name='update_project'),
    path('project/delete/<str:id>', views.delete_project, name='delete_project'),
    path('upload/file/<str:pk>', views.upload_image, name='upload_image'),
    path('project/view', views.project_list, name='project_list'),
    path('post/update/<post>', views.update_post, name='update_post'),
    path('post/delete/<pk>', views.delete_post, name='delete_post'),
    path('password/change', views.change_password, name='change_password'),
    path('user/review', views.user_review, name='user_review'),
    path('team/create', views.add_team, name='add_team'),
    path('setting/dashboard', views.dashboard, name='dashboard'),
    path('dashboard/add/skills', views.add_skill, name='add_skill'),
    path('dashboard/route/<flag>', views.dashboardRoute, name='dashboardRoute'),
    path('contact/update/<str:id>', views.update_contact, name='update_contact'),
    path('team/delete/<str:id>', views.delete_team, name='delete_team'),
    path('team/update/<str:id>', views.update_team, name='update_team'),
    path('feature/add', views.add_project_feature, name='add_feature'),
    path('technology/add', views.add_project_technology, name='add_technology'),
    path('contact/delete/<str:id>', views.delete_contact, name='delete_contact'),
    path('skill/delete/<str:id>', views.delete_skill, name='delete_skill'),
    path('skill/update/<str:id>', views.update_skill, name='update_skill'),
    path('liked/', views.like_view, name='like_view'),
    path('News/publish', views.publish_news, name='publish_news'),
    path('News/delete/<str:pk>', views.delete_news, name='delete_news'),
    path('News/update/<str:pk>', views.update_news, name='update_news'),
    path('featur/technology/manage/<str:slug>',views.manage_feature_technology, name='manage_feature_technology'),
    path('feature/update', views.update_feature, name='update_feature'),
    path('feature/delete/<str:pk>', views.delete_feature, name='delete_feature'),
    path('technology/delete/<str:pk>', views.delete_technology, name='delete_technology'),
    path('technology/update', views.update_technology, name='update_technology'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from hitcount.models import HitCountMixin



# Create your models here.

class Post(models.Model, HitCountMixin):
    #Relationship
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=250)
    text = models.TextField(max_length=1000)
    like = models.IntegerField(default=0)
    view = models.IntegerField(null=True, default=0)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title
 
    
class PostImage(models.Model):
    #Relationships
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images")

    def __str__(self):
        return self.post.title
    
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    position = models.CharField(max_length=100, blank=True, null=True)
    contact = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    picture = models.ImageField(default='default.svg', upload_to='profile_image', null=True, blank=True)

    def __str__(self):
        return self.user.username
    
class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    review = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.review
    
class Technology(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.name  

class Feature(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Team(models.Model):
    # =======RELATIONS======
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
   

    linkedin = models.CharField(max_length=100, null=True, blank=True)
    twitter = models.CharField(max_length=100, null=True, blank=True)
    facebook = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.user.username



class Project(models.Model):
    CATEGORY_CHOICES = [
        ('Business','Business'),
        ('Education','Education'),
        ('Social','Social'),
        ('Organization','Organization'),
    ]
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=500)
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)  
    # =========RELATIONS==========
    technology = models.ManyToManyField(Technology)
    feature = models.ManyToManyField(Feature)

    link = models.URLField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class ProjectImage(models.Model):
    project = models.ForeignKey(Project, null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to="project_images")

    def __str__(self) -> str:
        return self.project.name  
    

class Service(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    email = models.EmailField(max_length=100)
    phone = models.IntegerField()
    address = models.CharField(max_length=250)

    def __str__(self):
        return self.email
    
class Query(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=250)

    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length=100)
    logo = models.FileField(upload_to="logos")

    def __str__(self):
        return self.name
    
class News(models.Model):
    headline = models.CharField(max_length=150)
    body_text = models.TextField(max_length=300)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.headline

    

blog/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from .models import Comment, Contact, Feature, News, Post, PostImage, Profile, Project,Query, Skill, Team, Technology
from hitcount.views import HitCountDetailView
from .forms import (
    CommentForm,
    ContactForm,
      FeatureForm,
    NewsForm,
      TechnologyForm, 
      ProfileUpdateForm, 
      ProjectForm, 
      ProjectImageForm,
    QueryForm,
    SkillForm,
    TeamForm, 
      UserRegistrationForm, 
      BlogPostForm, 
      PostImageForm, 
      UserUpdateForm
)
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models.signals import (
    post_save,
    pre_save,
)
# import signals
from django.dispatch import receiver
@receiver(pre_save, sender=User)
def user_pre_save_receiver(instance, sender, *args, **kwargs):
    """
    before saved in the database
    """
    print(instance.username, instance.id)

@receiver(post_save, sender=User)
def user_created_handler(instance, created, sender, *args, **kwargs):
    if created:
        print(instance.username, "created")
# post_save.connect(user_created_handler, sender=User)
# Create your views here.

class PostDetailView(HitCountDetailView):
    model = Post
    template_name = "post_view.html"
    count_hit = True
    

    
def index(request):
    blogs = Post.objects.all().order_by('-created_at')[:3]
    project = Project.objects.all().order_by('-created_at')[:3]
    comments = Comment.objects.select_related('user').order_by('-created_at')[:5]
    skills = Skill.objects.all()
    team = Team.objects.all()
    num_project = project.count()
    num_team = team.count()
    news = News.objects.all().order_by('-created_at')
    
    contact = Contact.objects.all()
    query_form = QueryForm()
    if request.method == 'POST':
        query_form = QueryForm(request.POST)
        if query_form.is_valid():
            query_form.save()
            messages.success(request, "Your Query submitted. Thank Your !")
        else:
            messages.error(request, "Oops...something went wrong. please try again...")

   
    context = {
        'comments':comments,
        'blogs':blogs,
        'project':project,
        'team_member':team,
        'query_form':query_form,
        'contact':contact,
        'skills':skills,
        'num_project':num_project,
        'num_team':num_team,
        'news':news
        }
    
    return render(request, 'index.html', context)

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password )
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, "Invalid username or password !")

    return render(request, 'forms/signin.html')

def signup(request):
    user_form = UserRegistrationForm()
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data.get("username")
            user = user_form.save()
            messages.success(request, f"{username} registered successfully !")
            return redirect('blank_page', user)
        else:
            messages.error(request, "Form is not valid Sorry !")
            
    context = {
        'user_form':user_form
        }
    return render(request, 'forms/signup.html', context)

@login_required(login_url='/signin/')
def signout(request):
    logout(request)
    return render(request, 'index.html')


@login_required(login_url='/signin/')
def create_post(request):
    blog_post_form=BlogPostForm()
    image_form = PostImageForm()

    if request.method == 'POST':
        blog_post_form = BlogPostForm(request.POST)
        image_form = PostImageForm(request.POST, request.FILES)
        if blog_post_form.is_valid() and image_form.is_valid():
            blogPost = blog_post_form.save(commit=False)
            blogPost.user = request.user
            blogPost.save()

            imagePost = image_form.save(commit=False)
            imagePost.post = blogPost
            imagePost.save()
            messages.success(request, "Your Post created successfully !")
        else:
            messages.error(request, "Forms are invalid !")
    recent_post = Post.objects.filter(user=request.user).order_by('-created_at')[:5]      
    context = {
        'post_form':blog_post_form,
        'image_form':image_form,
        'recent_post':recent_post
    }   
    return render(request, 'forms/post_form.html', context)
@login_required(login_url='/signin/')
def update_post(request, post):
    blog = get_object_or_404(Post, id=post)
    postimage = PostImage.objects.filter(post=post)
    post_form = BlogPostForm(instance=blog)
    postimage_form = PostImageForm()
    print(postimage_form)
    if request.method == 'POST':
        post_form = BlogPostForm(request.POST, instance=blog)
        postimage_form = PostImageForm(request.POST, request.FILES)
        print(postimage_form)
        if post_form.is_valid() and postimage_form.is_valid():
            u_post = post_form.save()
            add_image = postimage_form.save(commit=False)
            add_image.post = u_post
            add_image.save()
            messages.success(request, 'Your post updated successfully !')
        else:
            messages.error(request, "Invalid Forms !")
    context = {
        'post_form':post_form,
        'postimage_form':postimage_form,
        'postimage':postimage
    }
    return render(request, 'forms/update_post.html', context)

@login_required(login_url='/signin/')
def delete_post(request, pk):
    if pk:
        Post.objects.get(id=pk).delete()
        messages.success(request, "Post deleted successfully !")
        return redirect('update_profile', request.user.id)
    

def post_view(request, pid):
    post = Post.objects.get(id=pid)
    all_posts = Post.objects.select_related('user').order_by('-created_at')
    context = {'post':post, 'all_posts':all_posts}
    return render(request, 'post_view.html', context)

@login_required(login_url='/signin/')
def update_profile(request, pk):
    user = get_object_or_404(User, id=pk)
    projects = Project.objects.all()
    posts = Post.objects.filter(user=request.user)
    user_form = UserUpdateForm(instance=user)
    profile_form = ProfileUpdateForm(instance=user.profile)
    user = User.objects.get(id=user.id)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            if Profile.objects.get(user=request.user):
                profile_form.save()
            else:
                profile = profile_form.save(commit=False)
                profile.user = request.user
                profile.save()
            messages.success(request, 'Profile updated ')
        else:
            messages.error(request, "Invalid Form...")
    
    context = {
        'user_form':user_form,
        'profile_form':profile_form,
        'user':user,
        'projects':projects,
        'posts':posts
    }
    return render(request, 'forms/update_profile.html', context)

@login_required(login_url='/signin/')
def project_view(request, pk):
    project = get_object_or_404(Project, id=pk)
    context = {
        'project':project
    }
    return render(request, 'project-details.html',context)

@login_required(login_url='/signin/')
def blog_view(request):
    return render(request, 'blogs_view.html')

@login_required(login_url='/signin/')
def add_project(request):
    if request.method == 'POST':
        project_form = ProjectForm(request.POST)
        image_form = ProjectImageForm(request.POST, request.FILES)
        if project_form.is_valid() and image_form.is_valid():
            pro = project_form.save()
            img = image_form.save(commit=False)
            img.project = pro
            img.save()
            messages.success(request, f"{pro} was added successfully. please upload project images.")

    return redirect('dashboardRoute', 5)

@login_required(login_url='/signin/')
def update_project(request, id):
    project = get_object_or_404(Project,id=id)
    if request.method == 'POST':
        project_form = ProjectForm(request.POST, instance=project)
        if project_form.is_valid():
            project_form.save()
            messages.success(request, "Project Updated !")
            return redirect('upload_image', id)
        else:
            messages.error(request, "Something went wrong !")
            return redirect('upload_image',id)
        
@login_required(login_url='/signin/')
def delete_project(request, id ):
    project = get_object_or_404(Project, id=id)
    if project:
        Project.objects.get(id=id).delete()
        messages.success(request, f"{project} deleted !")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='/signin/')        
def upload_image(request, pk):
    image_form = ProjectImageForm()
    project = Project.objects.get(id=pk)
    project_form = ProjectForm(instance=project)
    if request.method == 'POST':
        image_form = ProjectImageForm(request.POST, request.FILES)
        if image_form.is_valid():
            img = image_form.save(commit=False)
            img.project = project
            img.save()
        else:

templates/blogs_view.html
{% load static %}
{% include './links/link.html' %}
{% include './forms/sub-header.html' %}
{% load hitcount_tags %}

<div class="container pt-5 mt-5">
    
    <div class="section-header ">
        <h3>Blogs Feed</h3>
    </div>
    <section id="morePost" >
        <div class="container d-none more-post" data-aos="fade-up">
            {% for post in all_posts %}
            <div class="shadow p-4 rounded border my-3">
                <div class="content">
                    <img src="{{post.user.picture.url}}" alt="user profile">
                    {% if post.user.get_full_name %}
                    <h5 class="d-inline font-weight-bold">{{post.user.get_full_name}}</h5>
                    {% else %}
                    <h5 class="d-inline font-weight-bold">Admin</h5>
                    {% endif %}
                </div>
                <div class="post-container">
                    <h3 class="my-3 font-weight-bold">{{post.title}}</h3>
                    <p>{{post.text}}</p>
                    <p>
                        {% for pic in post.postimage_set.all %}
                        <img src="{{pic.image.url}}" class="post-image-all rounded " alt="image">
                        {% endfor %}
                        <p class="text-small">
                            <span class="text-secondary mr-2">updated at: </span>
                            <span class="">{{post.created_at}}</span>
                            <span class="ml-3"><i class="icofont-eye-alt"></i>&nbsp;</span>
                            <span class="text-secondary">{% get_hit_count for post %}</span>
                        </p>
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</div>
<!-- ========PAGE CONTAINER END======= -->
{% include './links/scripts.html' %}

templates/portfolio-details.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Portfolio Details</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  {% include './links/link.html' %}

  <!-- =======================================================
  * Template Name: BizPage - v3.1.0
  * Template URL: https://bootstrapmade.com/bizpage-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'forms/sub-header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Portfolio Details</h2>
          <ol>
            <li><a href="{%  url 'index' %}">Home</a></li>
            <li><a href="portfolio.html">Portfolio</a></li>
            <li>Portfolio Details</li>
          </ol>
        </div>

      </div>
    </section><!-- Breadcrumbs Section -->

    <!-- ======= Portfolio Details Section ======= -->
    <section class="portfolio-details">
      <div class="container">

        <div class="portfolio-details-container">

          <div class="owl-carousel portfolio-details-carousel">
            {% if project.project.projectimage_set.all %}
            {% for img in project.projectimage_set.all %}
            
            <img src="{{img.image.url}}" class="img-fluid project-image-slide" alt="">
            {% endfor %}
            {% else %}
            
              <img src="{% static 'img/portfolio/portfolio-details-1.jpg' %}" class="img-fluid" alt="">
              <img src="{% static 'img/portfolio/portfolio-details-2.jpg' %}" class="img-fluid" alt="">
            <img src="{% static 'img/portfolio/portfolio-details-3.jpg' %}" class="img-fluid" alt="">
            {% endif %}
          </div>

          <div class="portfolio-info">
            <h3>Project information</h3>
                <ul>
                  <li><strong>Category</strong>:{{project.category}}</li>
                  <li><strong>Technology</strong>:
                  {% for t in project.technology.all %}
                      <span>{{t.name}}</span> |
                  {% endfor %}
                  </li>
                  <li><strong>Project date</strong>: {{project.created_at}}</li>
                  <li><strong>Project URL</strong>: <a href="{{project.link}}">Source Code link&nbsp;<i class="icofont-long-arrow-right"></i></a></li>
                </ul>
          </div>

        </div>

        <div class="portfolio-description">
          <h2>{{project.name}}</h2>
          <p>{{project.description}}</p>
        </div>
      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>BizPage</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Home</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">About us</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Services</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>BizPage</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=BizPage
      -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- Vendor JS Files -->
{% include './links/scripts.html' %}
</body>

</html>

templates/post_view.html
{% load static %}
{% include './links/link.html' %}
{% include './forms/sub-header.html' %}
{% load hitcount_tags %}

<div class="container mt-5">


    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
          <div class="d-flex justify-content-between align-items-center">
            <h2>Blog Details</h2>
            <ol>
              <li><a href="{%  url 'index' %}">Home</a></li>
              <li><a href="{% url 'create_post' %}">Create Post</a></li>
              <li>Post Details</li>
            </ol>
          </div>
        </div>
      </section><!-- Breadcrumbs Section -->
    <!-- ======PAGE CONTENT===== -->
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-12 py-4">
            
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 pt-5">
            <div class="section-header ">
                <h3>Web Blogs</h3>
            </div>
            <div class="shadow border rounded p-4">
                <div class="row content">
                    <div class="col-md-1 col-lg-1 col-sm-1 col-xs-1">
                        <img src="{{post.user.profile.picture.url}}" class="user-avatar-active" alt="user profile">
                    </div>
                    <div class="col-md-11 col-lg-11 col-sm-11 col-xs-11 px-4 pt-2 pl-sm-5">
                    {% if post.user.get_full_name %}
                        <h5 class="d-inline font-weight-bold">{{post.user.get_full_name}}</h5>
                        <span class="">updated at: {{post.created_at}}</span>
                        <small>{{post.user.profile.position}}</small>
                        {% else %}
                        <h5 class="d-inline font-weight-bold">Admin</h5><br>
                        <small class="">updated at: {{post.created_at}}</small>
                    {% endif %}
                    </div>
                </div>
                <div class="post-container">
                    <h3 class="my-3 font-weight-bold">{{post.title}}</h3>
                    <p>{{post.text}}</p>
                    <p>
                        {% for pic in post.postimage_set.all %}
                        <img src="{{pic.image.url}}" class="post-image rounded " alt="image">
                        {% endfor %}
                        <p class="text-small">
                            
                            <span class="ml-3"><i class="icofont-eye-alt"></i>&nbsp;</span>
                            <span class="text-secondary">{% get_hit_count for post %}</span>
                            <span class="m-3"><a href="#">Share</a></span>
                            <span class="m-3 like-button" data-route-url="{% url 'like_view' %}" data-post-id="{{post.id}}" role="button">Like</span>
                        </p>
                    </p>
                </div>
            </div>
            <div class="my-3">
                <ul>
                    <li class="nav-menu" type="none">
                        <a href="#morePost" class="text-success" id="load-more-post">
                            <h3>see more post...</h3>
                        </a>
                    </li>
                </ul>
                
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12"> 
        </div>
    </div>
    <section id="morePost" >
        <div class="container d-none more-post" data-aos="fade-up">
            {% for post in all_posts %}
            <div class="shadow p-4 rounded border my-3">
                <div class="content">
                    <img src="{{post.user.profile.picture.url}}" class="user-avatar" 
                     alt="user profile">
                    {% if post.user.get_full_name %}
                    <h5 class="d-inline font-weight-bold">{{post.user.get_full_name}}</h5>
                    {% else %}
                    <h5 class="d-inline font-weight-bold">Admin</h5>
                    {% endif %}
                </div>
                <div class="post-container">
                    <h3 class="my-3 font-weight-bold">{{post.title}}</h3>
                    <p>{{post.text}}</p>
                    <p>
                        {% for pic in post.postimage_set.all %}
                        <img src="{{pic.image.url}}" class="post-image-all rounded " alt="image">
                        {% endfor %}
                        <p class="text-small">
                            <span class="text-secondary mr-2">updated at: </span>
                            <span class="">{{post.created_at}}</span>
                            <span class="ml-3"><i class="icofont-eye-alt"></i>&nbsp;</span>
                            <span class="text-secondary">{% get_hit_count for post %}</span>
                        </p>
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</div>
<!-- ========PAGE CONTAINER END======= -->
{% include './links/scripts.html' %}